### ISSUE TITLE
Map key '.' identifier crashes when using evy keywords

### ISSUE THREAD

**Issue by joshcarp** [evylang/evy#297]
keywords, which are _technically_ valid identifiers aren't allowed to be accessed or set via dot field assignment `map.fieldname`. This leads to this behaviour:
```
m:{}any
m.foobar = true
m["end"] = true
print m // {foobar:true end:true}
m.end = true // line 5: expected map key, found END
```

**Comment by juliaogris** [comment]
Add `lexer.AsIdent(tok token) (token, ok)` to lexer package for this.

**Comment by juliaogris** [comment]
Syntax highlighting will need to be aware of this special case.
