### ISSUE TITLE
Evy fmt converts string key map initialisations to string type

### ISSUE THREAD

**Issue by joshcarp** [evylang/evy#338]
Before formatting:
<img width="251" alt="image" src="https://github.com/evylang/evy/assets/32605850/e2402d5d-e131-4715-a3ce-947e9232e96d">

After formatting:

<img width="251" alt="image" src="https://github.com/evylang/evy/assets/32605850/3624751d-94ee-4a70-8431-c51bd00a02d8">

**Comment by joshcarp** [comment]
https://play.evy.dev/#content=H4sIAAAAAAAAE0tUsLJVqC4uKcrMS7cqKSpNreXiKijKzCtR0EjU5AIAzCy3Kx4AAAA=

**Comment by juliaogris** [comment]
```evy
a := { "a" : true }
print a
```

should be a syntax error. the correct version would be

```evy
a := { a : true }
print a
```
