### ISSUE TITLE
Reassignment mutates all references for mutable types

### ISSUE THREAD

**Issue by joshcarp** [evylang/evy#362]
I think @juliaogris and I already came across this. Not sure if this is expected but it seems like variable references are mutable and not just the underlying data.
For example in this case I would expect `orig` to never change from it's original value because it doesn't ever get re-assigned:

```evy
orig := {val:0 next:{}}
copy := orig

print "orig" orig // orig {val:0 next:{}}
print "copy" copy // copy {val:0 next:{}}

copy = copy.next.({}any)

print "orig" orig // orig {}
print "copy" copy // copy {}
```

This is the equivalent python code:

```python
orig = {"val": 0, "next": {}}
copy = orig

print("orig", orig)  # orig {'val': 0, 'next': {}}
print("copy", copy)  # copy {'val': 0, 'next': {}}

copy = copy["next"]

print("orig", orig)  # orig {'val': 0, 'next': {}}
print("copy", copy)  # copy {}
```

This also seems to be the case with slices:

```
orig := [1 2 3]
copy := orig

print "orig" orig // orig [1 2 3]
print "copy" copy // copy [1 2 3]

copy = copy[1:]

print "orig" orig // orig [2 3]
print "copy" copy // copy [2 3]

```

**Comment by camh-** [comment]
This is also broken for elements of arrays and maps. Some slightly simpler test cases:

Maps: https://play.evy.dev/#content=H4sIAAAAAAAAA0tUsLJVqE60MqzlSgIxE7mSFGwVqpOsjGq5Cooy80oUlBKVFBIV9PUVijPyS3NSFCCiYC0KSaUlEH4xqpYkJYUkLgC741kvWwAAAA==
```
a := {a: 1}
b := a
b = {b: 2}
print "a" a // should print {a:1} but prints {b:2}
print "b" b
```

Arrays:
https://play.evy.dev/#content=H4sIAAAAAAAAA0tUsLJViDaM5UoCMRK5khRsFaKNYrkKijLzShSUEpUUEhX09RWKM/JLc1IUIKLRhrEKSaUlEF4xsvIkJYUkLgArmnwwUwAAAA==
```
a := [1]
b := a
b = [2]
print "a" a // should print [1] but prints [2]
print "b" b
```

Map elements:
https://play.evy.dev/#content=H4sIAAAAAAAAA0tUsLJVqE60MqzlSoIwE60Sa7mSkdl6iYkKtgrVSVZGtVwFRZl5JQpKSUoKSQr6+grFGfmlOSkKEFGQerBRtQpJpSUQwWKIKEgvXHOykkIyFwAr+DfJeQAAAA==
```
a := {a:1}
b := {aa:a}
c := {aa:a}
c.aa = {b:2}
print "b" b // should print {aa:{a:1}} but prints {aa:{b:2}}
print "c" c
```

Array elements: https://play.evy.dev/#content=H4sIAAAAAAAAA0tUsLJViDZUMIrlSgIzE2O5kuGMaINYBVuFaGMFk1iugqLMvBIFpSQlhSQFfX2F4oz80pwUBYgo2ACFpNISCL8YVUuykkIyFwCO9BvWaQAAAA==
```
a := [1 2]
b := [a]
c := [a]
c[0] = [3 4]
print "b" b // should print [1 2] but prints [3 4]
print "c" c
```

**Comment by juliaogris** [comment]
wow, that was harder to fix than expected. Turns out the pratt parser in human-eval/160.evy had bug as well....
